### ISSUE TITLE
Time to train Inverter and Feature Editor

### ISSUE THREAD

**Issue by LiXm1002** [FusionBrainLab/StyleFeatureEditor#1]
Thanks for releasing code!
And I have some questions about training the network.
Both sfe_editor.pt and sfe_inverter.pt are very large, I wonder the time and equipment required to train these two models. I didn't found related information in paper.

**Comment by retir** [comment]
Thank you for your question! 
Indeed, the checkpoints we provide are very large. This is because during training we save every part of our pipeline including optimisers, discriminator and so on. In order to download checkpoints faster, we now upload lighter versions of our encoders (consisting only of encoders weights) to Hugging Face. The full (previous) version is uploaded to Google Drive (see links in README.md).

As for training time, we used a single A100 for each part of our pipeline. The first part requires about 300k images, with a batch size of 8 it took about 3 days. The second part requires about 200k images, with a batch size of 8 it also took about 3 days. If you have a different type of GPU, you can also check the approximate time left during training, which is logged at each `log_step` iteration.
