### ISSUE TITLE
About styleclip_directions editing

### ISSUE THREAD

**Issue by Li-Jijie** [FusionBrainLab/StyleFeatureEditor#11]
Hello, when I use the predefined descriptions, the edits related to styleclip_directions output images that are almost entirely white. Could you please give me some guidance on how to resolve this issue? (Other pretrained descriptions work fine.) Thank you!

**Comment by retir** [comment]
Hi, could you please give us some additional information about your editing, such as editing power, neutral prompt, target prompt and disentanglement?

**Comment by Li-Jijie** [comment]
![捕获](https://github.com/user-attachments/assets/4200d8d0-1a86-43e9-b98d-288a4c33a49b)

My editing settings are as follows, and I only modified the editing_name. Could it be an issue with the pretrained weights? The tests for other editing_name settings had no problems.

**Comment by retir** [comment]
Thank you for the information! The problem is that styleclip is much more sensitive to editing power then other methods. Appropriate power for styleclip directions is about [0; 0.18] range (you can check recommended ranges in `available_directions.txt`). Using power as [5, 6, 7, 8] will indeed cause massive artefacts.

**Comment by Li-Jijie** [comment]
Thank you so much, nice work!
