### ISSUE TITLE
how to improve result become blurry?

### ISSUE THREAD

**Issue by ersanliqiao** [FusionBrainLab/StyleFeatureEditor#5]
result become blurry

**Comment by retir** [comment]
Hello, could you please give us examples of blurred results and their original images?

**Comment by ersanliqiao** [comment]
can you add my qq? 771009283, i will give you my own image

**Comment by retir** [comment]
Sorry, but we do not have a qq account, could you please add images to this issue?

**Comment by ersanliqiao** [comment]
or give me a email? my personal image

**Comment by retir** [comment]
Okay, could you send images to bobkov@airi.net?

**Comment by retir** [comment]
Thank you for your examples! Let us give here another example of our method so that readers will be able to understand the problem. There is an original image:
<img src="https://github.com/user-attachments/assets/38220a19-f063-4799-b8c9-8d2ee58e992b" width="400">
and its inversion made by SFE:
<img src="https://github.com/user-attachments/assets/22e19d0a-49e8-4293-8a83-7e1006597892" width="400">

However, when using a high zoom level, the result for the original image is
<img src="https://github.com/user-attachments/assets/5bb4d261-6921-45fd-a1f4-e41894562416" width="400">

and the same part of the inversion:
<img src="https://github.com/user-attachments/assets/343aeeea-35e5-41d1-b491-c0e984bd0c21" width="400">

Unfortunately, although our method reconstructs details (such as make-up), it can actually blur images at high zoom levels. We are currently working on ways to improve SFE, particularly to overcome this drawback.
